spring:
  application:
   name: budgetManage
#   database config
  datasource:
    url: jdbc:mysql://localhost:3306/budget
    username: root
    password: TXTbirth@0912
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.genesisstudio.budgetManage.model
